Add testing function for ovs_switch and utils
John-Lin/tinynet pull request #9
Opened 2017-10-07 10:33 UTC by hwchiu

- Add new dependency for testing (I use testify)
- Add utils_test to testing for utils
- Add ovs_switch_test to testing for ovs_switch
- ovs_switch.go provide function to delete itself()
- Add travis to perform go test and coverage
- Modify README to add travis/coverage/godocs badge

2017-10-07 11:01 UTC, hwchiu commented
Reopen after fixing CI

2017-10-11 02:13 UTC, John-Lin requested changes

2017-10-11 02:13 UTC, John-Lin commented on .travis.yml
> +        on_success: changs
Should be `on_success: change`

2017-10-11 03:07 UTC, hwchiu commented
close to fix the rebase problem.

2017-10-11 03:07 UTC, closed without merging